In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('https://raw.githubusercontent.com/srinivasav22/Graduate-Admission-Prediction/master/Admission_Predict_Ver1.1.csv')

In [3]:
dataset.head()

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
0           1        337          118                  4  4.5   4.5  9.65   
1           2        324          107                  4  4.0   4.5  8.87   
2           3        316          104                  3  3.0   3.5  8.00   
3           4        322          110                  3  3.5   2.5  8.67   
4           5        314          103                  2  2.0   3.0  8.21   

   Research  Chance of Admit   
0         1              0.92  
1         1              0.76  
2         1              0.72  
3         1              0.80  
4         0              0.65

In [4]:
dataset.columns

Index(['Serial No.', 'GRE Score', 'TOEFL Score', 'University Rating', 'SOP',
       'LOR ', 'CGPA', 'Research', 'Chance of Admit '],
      dtype='object')

In [5]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Serial No.         500 non-null    int64  
 1   GRE Score          500 non-null    int64  
 2   TOEFL Score        500 non-null    int64  
 3   University Rating  500 non-null    int64  
 4   SOP                500 non-null    float64
 5   LOR                500 non-null    float64
 6   CGPA               500 non-null    float64
 7   Research           500 non-null    int64  
 8   Chance of Admit    500 non-null    float64
dtypes: float64(4), int64(5)
memory usage: 35.3 KB


In [6]:
dataset.describe().T

count       mean         std     min       25%     50%  \
Serial No.         500.0  250.50000  144.481833    1.00  125.7500  250.50   
GRE Score          500.0  316.47200   11.295148  290.00  308.0000  317.00   
TOEFL Score        500.0  107.19200    6.081868   92.00  103.0000  107.00   
University Rating  500.0    3.11400    1.143512    1.00    2.0000    3.00   
SOP                500.0    3.37400    0.991004    1.00    2.5000    3.50   
LOR                500.0    3.48400    0.925450    1.00    3.0000    3.50   
CGPA               500.0    8.57644    0.604813    6.80    8.1275    8.56   
Research           500.0    0.56000    0.496884    0.00    0.0000    1.00   
Chance of Admit    500.0    0.72174    0.141140    0.34    0.6300    0.72   

                      75%     max  
Serial No.         375.25  500.00  
GRE Score          325.00  340.00  
TOEFL Score        112.00  120.00  
University Rating    4.00    5.00  
SOP                  4.00    5.00  
LOR                  4.00    5.00  
CGPA                 9.04    9.92  
Research             1.00    1.00  
Chance of Admit      0.82    0.97

In [7]:
X=dataset.drop('Chance of Admit ',axis=1)

In [8]:
X.head()

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
0           1        337          118                  4  4.5   4.5  9.65   
1           2        324          107                  4  4.0   4.5  8.87   
2           3        316          104                  3  3.0   3.5  8.00   
3           4        322          110                  3  3.5   2.5  8.67   
4           5        314          103                  2  2.0   3.0  8.21   

   Research  
0         1  
1         1  
2         1  
3         1  
4         0

In [9]:
y=dataset['Chance of Admit ']

In [10]:
y.head()

0    0.92
1    0.76
2    0.72
3    0.80
4    0.65
Name: Chance of Admit , dtype: float64

In [11]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()

In [12]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.33,random_state=42)

In [13]:
X_train_tf=sc_X.fit_transform(X_train)

In [14]:
X_train_tf

array([[ 1.55816388e+00, -5.25174731e-01, -7.06985745e-01, ...,
         5.38819022e-01, -8.35765678e-01, -1.14470294e+00],
       [-1.64243247e+00,  4.77035981e-01,  2.76433873e-01, ...,
        -1.61323061e-03,  3.63045482e-01, -1.14470294e+00],
       [-1.77908715e+00, -7.98504925e-01, -1.03479228e+00, ...,
         5.38819022e-01, -1.15657430e+00, -1.14470294e+00],
       ...,
       [ 6.73504661e-01, -1.34516531e+00, -1.36259882e+00, ...,
        -1.62290999e+00, -2.25407747e+00, -1.14470294e+00],
       [ 1.29923923e+00, -7.07394861e-01, -3.79179206e-01, ...,
         5.38819022e-01, -1.52803691e+00, -1.14470294e+00],
       [-1.09581377e+00, -2.51844537e-01, -2.15275936e-01, ...,
        -1.61323061e-03, -5.65611050e-01, -1.14470294e+00]])

In [15]:
y_train

471    0.64
26     0.76
7      0.68
453    0.73
108    0.93
       ... 
106    0.87
270    0.72
348    0.57
435    0.55
102    0.62
Name: Chance of Admit , Length: 335, dtype: float64

In [16]:
from sklearn.svm import SVR
regressor = SVR(kernel = 'rbf')
regressor.fit(X_train_tf, y_train)

SVR()

In [17]:
X_train_tf[0]

array([ 1.55816388, -0.52517473, -0.70698575, -0.08288487, -1.38531121,
        0.53881902, -0.83576568, -1.14470294])

In [18]:
y_pred_value = regressor.predict([[ 1.55816388, -0.52517473, -0.70698575, -0.08288487, -1.38531121,
        0.53881902, -0.83576568, -1.14470294]])

In [19]:
y_pred_value

array([0.56360083])

In [20]:
regressor.score(X_train_tf,y_train)

0.8002696421631225

In [21]:
X_test_tf=sc_X.fit_transform(X_test)

In [22]:
y_pred=regressor.predict(X_test_tf)

In [23]:
y_pred

array([0.85673296, 0.73019046, 0.5828649 , 0.70356892, 0.75310372,
       0.85096704, 0.5041976 , 0.65482011, 0.73962739, 0.76460409,
       0.60065467, 0.7303861 , 0.63350246, 0.882785  , 0.80746064,
       0.45520624, 0.7877914 , 0.54507403, 0.52370054, 0.58872704,
       0.66935178, 0.54426431, 0.73717848, 0.79162789, 0.71818948,
       0.60307918, 0.84317784, 0.83598786, 0.62409522, 0.7601493 ,
       0.57317651, 0.76253485, 0.59110104, 0.84996208, 0.6094571 ,
       0.7734036 , 0.51294143, 0.88372624, 0.68805327, 0.67738031,
       0.87228365, 0.55207133, 0.6478665 , 0.86288206, 0.84184557,
       0.50829735, 0.87224878, 0.7686978 , 0.7682513 , 0.86345657,
       0.8286623 , 0.57610464, 0.69465166, 0.54578314, 0.90519033,
       0.58916226, 0.85202351, 0.62692024, 0.69192495, 0.47283271,
       0.60391225, 0.73636349, 0.60468729, 0.63319623, 0.48470594,
       0.5739233 , 0.84321247, 0.85218252, 0.684012  , 0.7024667 ,
       0.66672358, 0.80016083, 0.699498  , 0.6036373 , 0.51974

In [24]:
X_test['Chance_pred']=y_pred

In [25]:
X_test

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
361         362        334          116                  4  4.0   3.5  9.54   
73           74        314          108                  4  4.5   4.0  9.04   
374         375        315          105                  2  2.0   2.5  7.65   
155         156        312          109                  3  3.0   3.0  8.69   
104         105        326          112                  3  3.5   3.0  9.05   
..          ...        ...          ...                ...  ...   ...   ...   
110         111        305          108                  5  3.0   3.0  8.48   
318         319        324          111                  3  2.5   2.0  8.80   
428         429        316          103                  2  2.0   4.5  8.74   
29           30        310           99                  2  1.5   2.0  7.30   
437         438        317          106                  1  1.5   3.5  7.65   

     Research  Chance_pred  
361         1     0.856733  
73          1     0.730190  
374         0     0.582865  
155         0     0.703569  
104         1     0.753104  
..        ...          ...  
110         0     0.640934  
318         1     0.759723  
428         0     0.668538  
29          0     0.464871  
437         1     0.630738  

[165 rows x 9 columns]